### PR TITLE
[Release3] Bugs fixes

### PR DESCRIPTION
**Pull request by adityagajbhiye**
- test cases fix.
- guide lines fixed and updated(UI/UX guide).
-  hotfix issues fixed.

### CODE REVIEW

**Comment by Siegfriedk** [comment]
@adityagajbhiye i think you need to reference the fonts in your NOTICE or dependency file. @AngelikaWittek any thought?

**Comment by adityagajbhiye** [comment]
We have made suggested changes. Please review.

**Comment by Siegfriedk** [comment]
> We have made suggested changes. Please review.

@adityagajbhiye what did you clarify with @AngelikaWittek in regards of adding a hint for the fonts to the NOTICE file? I'm not seeing you giving me feedback on this topic?

**Comment by adityagajbhiye** [comment]
@Siegfriedk  Please review. We have made suggested changes.

**Comment by Siegfriedk** [comment]
@adityagajbhiye very weird, i got an email were you wrote that you made suggested changes but i cant find the update of the noticice file and i can't see any answer to my question?

**Comment by adityagajbhiye** [comment]
@Siegfriedk  We have made suggested changes in Notice.md file . Please review it.

**Pull request merged**
